'use client';
import { useMemo, useState } from 'react';
import { Bell, ChevronDown, ChevronRight, Flame, Menu, Plus, Trophy, X } from 'lucide-react';

type Fighter={name:string;style:string;gender:'M'|'F';sales:number;vgv:number;team:string;wins:string[];photo?:string};
const initial:Fighter[]=[
 {name:'Lucas Costa',style:'Muay Thai',gender:'M',sales:7,vgv:1730000,team:'BLACK HOUSE',wins:['Knockout · 1º round','Finalização · Submission','Vitória por pontos','Knockout · 1º round']},
 {name:'Pedro Augusto',style:'Jiu-Jitsu',gender:'M',sales:6,vgv:1490000,team:'IRON GROUND',wins:['Finalização · Submission','Vitória por pontos']},
 {name:'Yuri',style:'Kickboxing',gender:'M',sales:5,vgv:1270000,team:'WOLFPACK',wins:['Knockout · 1º round','Vitória por pontos']},
 {name:'Hércules',style:'Wrestling',gender:'M',sales:3,vgv:980000,team:'IRON GROUND',wins:['Finalização · Submission']},
 {name:'Malu Ribeiro',style:'Taekwondo',gender:'F',sales:2,vgv:720000,team:'BLACK HOUSE',wins:['Knockout · 1º round']},
 {name:'Lucas Silva',style:'Karatê',gender:'M',sales:1,vgv:490000,team:'WOLFPACK',wins:['Vitória por pontos']},
];
const events=[{name:'EVENTO 01',sub:'QUALIFICATÓRIA',goal:2500000,belt:'CINTURÃO QUALIFIER',prize:'PRIMEIRA VENDA · R$ 500'}, {name:'EVENTO 02',sub:'MAIN EVENT',goal:3500000,belt:'CINTURÃO MAIN EVENT',prize:'PREMIAÇÃO META 2'}, {name:'EVENTO 03',sub:'UNIFICAÇÃO',goal:5000000,belt:'CINTURÃO UNIFICADO',prize:'GRANDE FINAL'}];
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
const category=(n:number)=>n>=5?'PESO PESADO':n>=3?'MEIO-PESADO':n>=1?'PESO LEVE':'ESTREANTE';
export default function Home(){
 const [fighters,setFighters]=useState(initial); const [modal,setModal]=useState(false); const [open,setOpen]=useState(false); const [notice,setNotice]=useState('');
 const [form,setForm]=useState({fighter:initial[0].name,value:'',result:'Knockout · 1º round',note:''});
 const ranked=useMemo(()=>[...fighters].sort((a,b)=>b.vgv-a.vgv),[fighters]);
 const total=ranked.reduce((s,f)=>s+f.vgv,0); const leads=ranked.slice(0,2); const winner=ranked[0];
 const award=(e:React.FormEvent)=>{e.preventDefault();const amount=Number(form.value);if(!amount)return;setFighters(fs=>fs.map(f=>f.name===form.fighter?{...f,vgv:f.vgv+amount,sales:f.sales+1,wins:[form.result,...f.wins]}:f));setNotice(`VITÓRIA REGISTRADA · ${form.fighter.toUpperCase()} · ${form.result.toUpperCase()}`);setModal(false);setTimeout(()=>setNotice(''),4800);};
 return <main>
  <header className="top"><button className="icon mobile" aria-label="Menu"><Menu/></button><a href="#"><img src="/assets/umc-mark.svg" alt="UMC Ultimate Menfe Championship"/></a><nav><a href="#eventos">EVENTOS</a><a href="#main-event">MAIN EVENT</a><a href="#fighters">LUTADORES</a><a href="#historico">VITÓRIAS</a></nav><button className="notice" onClick={()=>setModal(true)}><Bell size={17}/><span>REGISTRAR VITÓRIA</span></button><button className="avatar-mini">LJ</button></header>
  <div className="ticker"><span>UMC · OCTOBER 2026</span><i/> <span>ULTIMATE MENFE CHAMPIONSHIP</span><i/><b>LIVE</b><i/><span>3 EVENTOS · 3 CINTURÕES · 1 CAMPEÃO</span></div>
  <section className="hero"><div className="hero-back"/><div className="hero-content"><div className="eyebrow"><span className="live-dot"/> TEMPORADA DE OUTUBRO 2026</div><h1>O OCTAGON<br/><em>É SEU.</em></h1><p className="hero-tag">CADA VENDA É UMA LUTA. CADA VITÓRIA CONSTRÓI UM CAMPEÃO.</p><div className="hero-actions"><a className="btn-gold" href="#eventos">VER OS EVENTOS <ChevronRight size={16}/></a><button className="btn-outline" onClick={()=>setOpen(true)}>ESCOLHER MEU ESTILO</button></div><div className="hero-stats"><div><b>{fighters.length.toString().padStart(2,'0')}</b><span>LUTADORES</span></div><div><b>{money(total)}</b><span>VGV NO OCTAGON</span></div><div><b>03</b><span>CINTURÕES EM JOGO</span></div></div></div><div className="hero-stamp"><span>MENFE</span><b>OCTAGON</b><small>THE FIGHT FOR GREATNESS</small></div><div className="hero-bottom">ULTIMATE MENFE CHAMPIONSHIP <span>·</span> ENTRE NA ARENA. CONSTRUA SEU CARTEL.</div></section>
  <section className="belt-section" id="eventos"><div className="section-head"><div><div className="eyebrow">ROAD TO THE BELT</div><h2>TRÊS EVENTOS. <em>TRÊS CONQUISTAS.</em></h2></div><div className="goal-total"><span>VGV DA OPERAÇÃO</span><b>{money(total)}</b></div></div><div className="progress-wrap"><div className="progress" style={{width:`${Math.min(total/5000000*100,100)}%`}}/><div className="progress-points">{events.map((e,i)=><span key={e.name} style={{left:`${e.goal/5000000*100}%`}} className={total>=e.goal?'done':''}><i/><small>EVENTO 0{i+1}</small></span>)}</div></div><div className="event-grid">{events.map((e,i)=><article className={`event-card ${total>=e.goal?'won':''}`} key={e.name}><div className="event-top"><span>{e.name}</span><span className="round">{total>=e.goal?'CONCLUÍDO':`0${i+1} / 03`}</span></div><div className="belt-icon"><Trophy size={25}/><span>{i===2?'UNDISPUTED':i===1?'MAIN EVENT':'QUALIFIER'}</span></div><h3>{e.sub}</h3><p>{e.belt}</p><strong>{money(e.goal)}</strong><div className="event-foot">{total>=e.goal?'VENCEDOR DO EVENTO: ':''}{total>=e.goal?winner.name:e.prize}</div></article>)}</div><p className="event-rule">Ao concluir cada etapa, o lutador com maior VGV acumulado é declarado vencedor daquele evento. A primeira venda do executivo vale <b>R$ 500</b>.</p></section>
  <section className="main-event" id="main-event"><div className="main-label"><span className="live-dot"/> MAIN EVENT <small>· TOP 2 EM VGV</small></div><div className="versus">{leads.map((f,i)=><article className={`fighter-side ${i?'right':''}`} key={f.name}><div className="fighter-image"><img src={f.photo||'/assets/fighter-placeholder.svg'} alt={`Avatar de ${f.name}`}/><div className="photo-overlay"><span>{f.team}</span><b>{f.name}</b></div></div><div className="fighter-info"><small>{i?'CONTENDER #1':'CURRENT CHAMPION'}</small><h3>{f.name}</h3><span className="fight-style">{f.style} <i/> {f.gender==='F'?'FEMININO':'MASCULINO'}</span><div className="fighter-data"><div><span>VGV</span><b>{money(f.vgv)}</b></div><div><span>VITÓRIAS</span><b>{f.sales}–0</b></div><div><span>CATEGORIA</span><b>{category(f.sales)}</b></div></div></div></article>)}<div className="versus-mark">VS</div></div><div className="fight-note"><span>MAIN EVENT · RANKING AO VIVO</span><b>{money(Math.abs(leads[0].vgv-leads[1].vgv))} <small>DE DIFERENÇA</small></b><span>PRÓXIMA VENDA PODE MUDAR O CAMPEÃO</span></div></section>
  <section className="fighters-section" id="fighters"><div className="section-head"><div><div className="eyebrow">O CARD OFICIAL</div><h2>OS <em>LUTADORES.</em></h2></div><button className="btn-outline" onClick={()=>setOpen(true)}>MEU PERFIL <ChevronRight size={16}/></button></div><div className="fighter-grid">{ranked.map((f,i)=><article className="roster-card" key={f.name}><div className="roster-img"><img src={f.photo||'/assets/fighter-placeholder.svg'} alt=""/><span className="rank">#{String(i+1).padStart(2,'0')}</span><span className="weight">{category(f.sales)}</span><b>{f.team}</b></div><div className="roster-content"><div><h3>{f.name}</h3><span>{f.style} · {f.gender==='F'?'F':'M'}</span></div><div className="roster-values"><b>{money(f.vgv)}</b><small>{f.sales} VITÓRIAS</small></div><div className="record-row"><span>CARTEL</span><b>{String(f.sales).padStart(2,'0')}–00</b><button onClick={()=>{setForm({...form,fighter:f.name});setModal(true)}}>+ RESULTADO</button></div></div></article>)}</div></section>
  <section className="win-section" id="historico"><div className="section-head"><div><div className="eyebrow">DING DING · VICTORY</div><h2>ÚLTIMAS <em>VITÓRIAS.</em></h2></div><button className="btn-gold" onClick={()=>setModal(true)}>REGISTRAR VENDA <Plus size={16}/></button></div><div className="win-list">{ranked.flatMap(f=>f.wins.map((w,i)=>({f,w,i}))).slice(0,8).map(({f,w,i},n)=><div className="win-row" key={`${f.name}-${n}`}><span className="win-icon"><Flame size={17}/></span><b>{f.name}</b><span className="win-type">{w}</span><span className="win-meta">{n===0?'HOJE':`${n+1} OUT`}</span><ChevronRight size={16}/></div>)}</div></section>
  <footer><img src="/assets/umc-mark.svg" alt="UMC"/><span>USO INTERNO · MENFE INCORPORADORA</span><span>OCTOBER 2026 · OCTAGON</span></footer>
  {notice&&<div className="toast">{notice}</div>}
  {modal&&<div className="modal-back" onClick={()=>setModal(false)}><form className="modal" onSubmit={award} onClick={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={()=>setModal(false)}><X/></button><div className="eyebrow">DING DING · NEW VICTORY</div><h2>REGISTRAR <em>VITÓRIA</em></h2><label>LUTADOR<select value={form.fighter} onChange={e=>setForm({...form,fighter:e.target.value})}>{fighters.map(f=><option key={f.name}>{f.name}</option>)}</select></label><label>VALOR DA VENDA (VGV)<input required type="number" min="1" value={form.value} onChange={e=>setForm({...form,value:e.target.value})} placeholder="Ex.: 249900"/></label><label>TIPO DE VITÓRIA<select value={form.result} onChange={e=>setForm({...form,result:e.target.value})}><option>Knockout · 1º round</option><option>Finalização · Submission</option><option>Vitória por pontos</option></select></label><label>HISTÓRIA DA LUTA <small>(opcional)</small><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Objeções, tempo de negociação, contexto…"/></label><button className="btn-gold submit">CONFIRMAR VITÓRIA <ChevronRight size={16}/></button><p className="modal-help">Primeira vitória do executivo no mês: premiação de R$ 500.</p></form></div>}
  {open&&<div className="modal-back" onClick={()=>setOpen(false)}><div className="modal profile-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setOpen(false)}><X/></button><div className="eyebrow">CONFIGURE SEU FIGHTER</div><h2>ESCOLHA SUA <em>IDENTIDADE.</em></h2><label>ESTILO DE LUTA<select><option>Jiu-Jitsu</option><option>Karatê</option><option>Muay Thai</option><option>Kickboxing</option><option>Wrestling</option><option>Taekwondo</option></select></label><label>DIVISÃO<select><option>Masculino</option><option>Feminino</option></select></label><label>FOTO DO ROSTO<input type="file" accept="image/*"/><small>O rosto será recortado e aplicado ao avatar de lutador.</small></label><button className="btn-gold submit" onClick={()=>setOpen(false)}>SALVAR PERFIL <ChevronRight size={16}/></button></div></div>}
 </main>
}
